name: Workflow Run Basic
run-name: Running - Workflow Run Basic

on:
  workflow_run:
    workflows: ["Trigger"]
    types:
      - completed

jobs:
  basic-job:
    runs-on: ubuntu-latest
    steps:
      - name: comentário
        run: echo "Workflow run completed foi triggado"
